### ISSUE TITLE
Callback appends to writer, but position is not updated

### ISSUE THREAD

**Issue by dralves** [khonsulabs/okaywal#8]
This is more of a question that an issue.
On `entry.rs`:
```
    pub(crate) fn commit_and<F: FnOnce(&mut LogFileWriter<M::File>) -> io::Result<()>>(
        mut self,
        callback: F,
    ) -> io::Result<EntryId> {
        let file = self.file.take().expect("already committed");

        let mut writer = file.lock();

        writer.write_all(&[END_OF_ENTRY])?;
        let new_length = writer.position();
        callback(&mut writer)?;
        writer.set_last_entry_id(Some(self.id));
        drop(writer);

        self.log.reclaim(file, WriteResult::Entry { new_length })?;

        Ok(self.id)
    }
```
The entry is finished with `writer.write_all(&[END_OF_ENTRY])?;` the position is taken and only then callback is called. This seems weird because the writer is passed to the callback which seems to indicate that the callback will write more bytes (and thus terminating the entry and new_length should be called after calling the callback and not before). 

Within the project this is only used in one test (aborted_entry) so I'm not sure this is a purposeful feature or mostly a test fixture.

**Comment by ecton** [comment]
It's a test abstraction. As long as the test is able to still test what it's testing, I'm not opposed to changing where the length is copied from. However, I'm suspicious of what data you can write after the end of entry that will end up being valid. In theory, there are no valid bytes that can be written after `END_OF_ENTRY` except `NEW_ENTRY`.

**Comment by dralves** [comment]
thanks you for the clarity. closing
